// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using courtbookingAPIREST.Common.Infrastructure;

#nullable disable

namespace courtbookingAPIREST.Common.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("courtbookingAPIREST.Domain.Clubs.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Clubs.ClubSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("club_schedules_id");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("interval")
                        .HasColumnName("closing_time");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("interval")
                        .HasColumnName("opening_time");

                    b.Property<Guid?>("club_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("club_id");

                    b.ToTable("club_schedules", (string)null);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Clubs.ClubScheduleException", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("club_schedule_exceptions_id");

                    b.Property<TimeSpan?>("ClosingTime")
                        .HasColumnType("interval")
                        .HasColumnName("closing_time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_closed");

                    b.Property<TimeSpan?>("OpeningTime")
                        .HasColumnType("interval")
                        .HasColumnName("opening_time");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("club_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("club_id");

                    b.ToTable("club_schedule_exceptions", (string)null);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Courts.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<bool>("OverridesClub")
                        .HasColumnType("boolean")
                        .HasColumnName("overrides_club");

                    b.Property<TimeSpan>("SlotDuration")
                        .HasColumnType("interval")
                        .HasColumnName("slot_duration");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("courts", (string)null);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Courts.CourtOperatingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("court_operating_schedules_id");

                    b.Property<TimeSpan>("ClosingTime")
                        .HasColumnType("interval")
                        .HasColumnName("closing_time");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("day_of_week");

                    b.Property<TimeSpan>("OpeningTime")
                        .HasColumnType("interval")
                        .HasColumnName("opening_time");

                    b.Property<Guid?>("court_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("court_id");

                    b.ToTable("court_operating_schedules", (string)null);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Courts.CourtTimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("court_time_slot_id");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("interval")
                        .HasColumnName("end");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("interval")
                        .HasColumnName("start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CourtId", "Date");

                    b.ToTable("court_time_slots", (string)null);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Geography.City", b =>
                {
                    b.Property<int>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("state_id")
                        .HasColumnType("integer");

                    b.HasKey("CityId");

                    b.HasIndex("state_id");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Geography.State", b =>
                {
                    b.Property<int>("StateId")
                        .HasColumnType("integer")
                        .HasColumnName("state_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("StateId");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Clubs.Club", b =>
                {
                    b.OwnsOne("courtbookingAPIREST.Domain.Geography.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("ClubId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.HasKey("ClubId");

                            b1.ToTable("clubs");

                            b1.WithOwner()
                                .HasForeignKey("ClubId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Clubs.ClubSchedule", b =>
                {
                    b.HasOne("courtbookingAPIREST.Domain.Clubs.Club", null)
                        .WithMany("Schedules")
                        .HasForeignKey("club_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Clubs.ClubScheduleException", b =>
                {
                    b.HasOne("courtbookingAPIREST.Domain.Clubs.Club", null)
                        .WithMany("ScheduleExceptions")
                        .HasForeignKey("club_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Courts.Court", b =>
                {
                    b.HasOne("courtbookingAPIREST.Domain.Clubs.Club", null)
                        .WithMany("Courts")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Courts.CourtOperatingSchedule", b =>
                {
                    b.HasOne("courtbookingAPIREST.Domain.Courts.Court", null)
                        .WithMany("OperatingSchedules")
                        .HasForeignKey("court_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Courts.CourtTimeSlot", b =>
                {
                    b.HasOne("courtbookingAPIREST.Domain.Courts.Court", null)
                        .WithMany()
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Geography.City", b =>
                {
                    b.HasOne("courtbookingAPIREST.Domain.Geography.State", "State")
                        .WithMany()
                        .HasForeignKey("state_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Clubs.Club", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("ScheduleExceptions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("courtbookingAPIREST.Domain.Courts.Court", b =>
                {
                    b.Navigation("OperatingSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
